const Items = [
  //Appetizers
  {
    name: "Egg Rolls",
    price: 6.0,
    description: "3 crispy eggrolls with cabbage, carrots",
    isSpicy: false,
    isVegan: false,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366657/China%20Center/Food%20Items/Apps/Eggroll_yj9gsj.jpg",
  },
  {
    name: "Fried Wonton",
    price: 7.5,
    description: "12 crispy fried wonton skins",
    isSpicy: false,
    isVegan: false,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366674/China%20Center/Food%20Items/Apps/Fried_Wtn_ngrl96.jpg",
  },
  {
    name: "Potstickers",
    price: 10.5,
    description: "8 potstickers filled with pork, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366679/China%20Center/Food%20Items/Apps/Pot_Stickers_at8ss2.jpg",
  },
  {
    name: "Fried Prawns",
    price: 10.5,
    description: "8 fried prawns",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366668/China%20Center/Food%20Items/Apps/Fried_Prawns_uwwgts.jpg",
  },
  {
    name: "Barbecue Pork",
    price: 10.5,
    description: "barbeque pork made in house",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366496/China%20Center/Food%20Items/Apps/BBQ_Pork_y3lrin.jpg",
  },
  {
    name: "Fried Chicken Wings",
    price: 10.95,
    description: "8 fried chicken wings",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677459944/China%20Center/Food%20Items/Apps/fr_ch_wing_bkwpz5.jpg",
  },
  {
    name: "Fried Squid",
    price: 10.95,
    description: "8 tender fried squid",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1678137749/China%20Center/Food%20Items/Apps/fried_squidies_cm3bcp.jpg",
  },
  {
    name: "Cream Cheese Crab Puff",
    price: 10.95,
    description:
      "10 cream cheese crab puffs with imitation crab, onions, cream cheese",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: false,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677990647/China%20Center/Food%20Items/Apps/ccp_a0zda1.jpg",
  },
  {
    name: "Assorted Appetizer (For 2)",
    price: 22.5,
    description: "all appetizers in one big serving",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: false,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl: "",
  },
  {
    name: "French Fries",
    price: 6.0,
    description: "crispy fried french fries",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1678221243/China%20Center/Food%20Items/Apps/crinkle_cut_fuapzz.jpg",
  },
  {
    name: "Shrimp Chips",
    price: 6.0,
    description:
      "colorful fried prawn chips made with dried shrimp powder, tapioca flour",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366685/China%20Center/Food%20Items/Apps/Shrimp_Chips_hpj1tj.jpg",
  },
  // Wonton Noodle Soup
  {
    name: "Hot & Sour Soup",
    price: 10.95,
    description:
      "pork, tofu, bamboo shoot, wood ear mushroom, creamy egg mixture",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787814/China%20Center/Food%20Items/Soup/hot_n_sour_rzn0uh.jpg",
  },
  {
    name: "Seaweed Soup",
    price: 10.95,
    description:
      "chicken, seaweed, snap peas, mushroom, bamboo shoot, egg mixture",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366014/China%20Center/Food%20Items/Soup/Seaweed_Sp_fu1u0b.jpg",
  },
  {
    name: "Egg Flower Soup",
    price: 10.95,
    description: "chicken, tofu, celery, mushroom, creamy egg mixture",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677365997/China%20Center/Food%20Items/Soup/Eggflower_Soup_l4iaxx.jpg",
  },
  {
    name: "Corn Chicken Soup",
    price: 10.95,
    description: "chicken, corn, creamy egg mixture",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679016156/China%20Center/Food%20Items/Soup/corn_ch_pyzyln.jpg",
  },
  {
    name: "Plain Wonton Soup (L)",
    price: 10.95,
    description: "12 pork filled wontons",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl: "",
  },
  {
    name: "Plain Wonton Soup (S)",
    price: 3.0,
    description: "2 pork filled wontons",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366031/China%20Center/Food%20Items/Soup/Small_Wtn_rd4byo.jpg",
  },
  {
    name: "Shrimp Sizzling Rice Soup",
    price: 12.95,
    description:
      "crispy sizzling rice, shrimp, mushroom, bamboo shoot, water chestnut, snap peas",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366026/China%20Center/Food%20Items/Soup/Siz_Sp_cvfxmq.jpg",
  },
  {
    name: "Pork Wonton and/or Noodle Soup",
    price: 12.95,
    description:
      "pork filled wontons, pork, bok choy, shitake mushrooms, bamboo shoot, water chestnut. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl: "",
  },
  {
    name: "Chicken Wonton and/or Noodle Soup",
    price: 12.95,
    description:
      "pork filled wontons, chicken, bok choy, shitake mushrooms, bamboo shoot, water chestnut. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677365944/China%20Center/Food%20Items/Soup/Ch_Wtn_Ndl_vyucx0.jpg",
  },
  {
    name: "Beef Wonton and/or Noodle Soup",
    price: 12.95,
    description:
      "pork filled wontons, beef, bok choy, shitake mushrooms, bamboo shoot, water chestnut. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787275/China%20Center/Food%20Items/Soup/bf_wtn_mtjyy2.jpg",
  },
  {
    name: "Combo Sizzling Rice Soup",
    price: 13.95,
    description:
      "crispy sizzling rice, chicken, pork, shrimp, mushroom, bamboo shoot, water chestnut",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366026/China%20Center/Food%20Items/Soup/Siz_Sp_cvfxmq.jpg",
  },
  {
    name: "Wor Wonton and/or Noodle Soup",
    price: 13.95,
    description:
      "pork filled wontons, chicken, pork, shrimp, bok choy, shitake mushrooms, bamboo shoot, water chestnut. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366042/China%20Center/Food%20Items/Soup/WWT_lqolqa.jpg",
  },
  {
    name: "Shrimp Wonton and/or Noodle Soup",
    price: 13.95,
    description:
      "pork filled wontons, shrimp, bok choy, shitake mushrooms, bamboo shoot, water chestnut. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366020/China%20Center/Food%20Items/Soup/Shr_Wtn_jq83ub.jpg",
  },
  {
    name: "Seafood Wonton and/or Noodle Soup",
    price: 14.95,
    description:
      "pork filled wontons, shrimp, fish fillet, squid, bok choy, shitake mushrooms, bamboo shoot, water chestnut. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1678137780/China%20Center/Food%20Items/Soup/seafood_wtn_u59xbb.jpg",
  },
  {
    name: "Seafood Sizzling Rice Soup",
    price: 14.95,
    description:
      "crispy sizzling rice, imitation crab meat, fish, shrimp, mushroom, bamboo shoot, water chestnut",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1678137773/China%20Center/Food%20Items/Soup/siz_sf_sp_yxicn8.jpg",
  },
  // Fried Rice
  {
    name: "Steamed Rice (S)",
    price: 2.0,
    description: "small steamed rice",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677460033/China%20Center/Food%20Items/Fried%20Rice/sm_rice_txyd3i.jpg",
  },
  {
    name: "Steamed Rice (L)",
    price: 3.0,
    description: "large steamed rice",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677460030/China%20Center/Food%20Items/Fried%20Rice/large_rice_gkqbqy.jpg",
  },
  {
    name: "Chicken Fried Rice",
    price: 9.5,
    description: "fried rice, egg, chicken, green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677459821/China%20Center/Food%20Items/Fried%20Rice/ch_fried_rice_ripmsg.jpg",
  },
  {
    name: "Pork Fried Rice",
    price: 9.5,
    description: "fried rice, egg, pork, peas, carrots",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367115/China%20Center/Food%20Items/Fried%20Rice/P_FR_z1c6i8.jpg",
  },
  {
    name: "Beef Fried Rice",
    price: 9.5,
    description: "fried rice, egg, beef, & green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 3,
    imageUrl: "",
  },
  {
    name: "Vegetable Fried Rice",
    price: 9.5,
    description: "fried rice, egg, beansprouts, peas, carrots, green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367107/China%20Center/Food%20Items/Fried%20Rice/Fried_Rice_VEG_f9kcpl.jpg",
  },
  {
    name: "Special Fried Rice",
    price: 10.5,
    description: "fried rice, egg, pork, chicken, shrimp, peas, carrots",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367102/China%20Center/Food%20Items/Fried%20Rice/Fried_Rice_SP_t1fh9g.jpg",
  },
  {
    name: "Shrimp Fried Rice",
    price: 10.5,
    description: "fried rice, egg, shrimp, green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787088/China%20Center/Food%20Items/Fried%20Rice/shr_fr_gqnuui.jpg",
  },

  //Chow Mein
  {
    name: "Plain Chow Mein",
    price: 9.95,
    description: "stir fried noodles, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787173/China%20Center/Food%20Items/Noods/plain_cm_bie4u8.jpg",
  },
  {
    name: "Chicken Chow Mein",
    price: 10.95,
    description: "stir fried noodles, chicken, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl: "",
  },
  {
    name: "Chicken Almond Chow Mein",
    price: 10.95,
    description: "stir fried noodles,chicken, almonds, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367027/China%20Center/Food%20Items/Noods/Ch_Almond_CM_yczh06.jpg",
  },
  {
    name: "Pork Chow Mein",
    price: 10.95,
    description: "stir fried noodles with pork, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl: "",
  },
  {
    name: "Vegetable Chow Mein",
    price: 10.95,
    description:
      "stir fried noodles, broccoli, carrots, bokchoy, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787123/China%20Center/Food%20Items/Noods/veg_cm_sooolf.jpg",
  },
  {
    name: "Special Chow Mein",
    price: 11.5,
    description:
      "stir fried noodles, pork, chicken, shrimp, beansprouts, cabbage, snow peas",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367046/China%20Center/Food%20Items/Noods/SP_CM_wwh9hi.jpg",
  },
  {
    name: "Shrimp Chow Mein",
    price: 11.5,
    description: "stir fried noodles, shrimp, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367040/China%20Center/Food%20Items/Noods/Shr_Cm_d0cldk.jpg",
  },
  {
    name: "Beef Chow Mein",
    price: 11.5,
    description: "stir fried noodles, beef, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367024/China%20Center/Food%20Items/Noods/Bf_CM_cyh005.jpg",
  },
  {
    name: "Beef Tomato Chow Mein",
    price: 11.5,
    description:
      "stir fried noodles, beef, tomato, green bell pepper, onion, beansprouts, cabbage, tomato sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl: "",
  },
  {
    name: "B.B.Q. Pork Chow Mein",
    price: 10.95,
    description: "stir fried noodles, barbeque pork, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl: "",
  },
  {
    name: "Pansit",
    price: 11.5,
    description: "rice stick noodles, egg, beansprouts, choice of protein",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367032/China%20Center/Food%20Items/Noods/CH_Pansit_yohwdi.jpg",
  },
  {
    name: "Beef Chow Fun",
    price: 12.95,
    description: "thick rice stick noodle, beef, beansprouts, green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367018/China%20Center/Food%20Items/Noods/Bf_Chowfun_zgip65.jpg",
  },
  {
    name: "Seafood Chow Mein",
    price: 12.95,
    description:
      "stir fried noodles, squid, shrimp, beansprouts, cabbage, snow peas",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl: "",
  },
  {
    name: "Shrimp Chow Fun",
    price: 13.95,
    description:
      "rice stick noodle stir fried with shrimp, beansprouts, green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl: "",
  },
  {
    name: "Singapore Chow Mein",
    price: 13.95,
    description:
      "rice stick noodle stir fried with choice of protein, egg, beansprouts, curry sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787893/China%20Center/Food%20Items/Noods/singapore_chow_mein_mkpp8x.jpg",
  },
  {
    name: "House Pan Fried Noodle Sizzling Plate",
    price: 16.5,
    description:
      "crispy pan fried noodles, special sauce, choice of protein, veggies",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677459991/China%20Center/Food%20Items/Noods/hot_plate_trw5wn.jpg",
  },
  //Beef
  {
    name: "Beef Broccoli",
    price: 13.95,
    description: "stir fried beef, broccoli",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366827/China%20Center/Food%20Items/Beef/Brocc_BF_g7kzda.jpg",
  },
  {
    name: "Ginger Beef",
    price: 14.95,
    description: "stir fried beef, ginger, green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679016213/China%20Center/Food%20Items/Beef/ginger_bf_abpwsb.jpg",
  },
  {
    name: "Beef with Oyster Sauce",
    price: 14.95,
    description: " stir fried beef, oyster sauce, veggies",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef with Tomato",
    price: 14.95,
    description: "stir fried beef, tomatoes, tomato sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef with Beansprouts",
    price: 14.95,
    description: "stir fried beef, beansprouts",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },

  {
    name: "Beef with Chinese Greens",
    price: 14.95,
    description: "stir fried beef, baby bok choy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1678137792/China%20Center/Food%20Items/Beef/bf_bok_choy_dekwxp.jpg",
  },
  {
    name: "Beef with Tofu",
    price: 14.95,
    description: "stir fried beef, tofu",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1678220759/China%20Center/Food%20Items/Beef/bf_tofu_xhuv67.jpg",
  },
  {
    name: "Beef with Cashew Nut",
    price: 14.95,
    description: "stir fried beef, cashews, veggies",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Green Pepper Beef",
    price: 14.95,
    description: "stir fried beef, green bell peppers",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef with Assorted Vegetables",
    price: 14.95,
    description: "stir fried beef, assorted vegetables",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef Bittermelon",
    price: 14.95,
    description: "stir fried beef, bittermelon",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Curry Beef",
    price: 14.95,
    description: "stir fried beef, veggies, curry sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Kung Pao Beef",
    price: 14.95,
    description: "stir fried beef, hot chilis, veggies, peanuts",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787186/China%20Center/Food%20Items/Beef/kp_bf_vvfu4m.jpg",
  },
  {
    name: "Szechuan Beef",
    price: 14.95,
    description: "stir fried beef, hot chilis, cabbage, wood ear mushroom",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Mongolian Beef",
    price: 16.95,
    description:
      "stir fried beef, hot chilis, mushrooms, bamboo shoots, green onions",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677460071/China%20Center/Food%20Items/Beef/mong_bf_wcgrux.jpg",
  },
  {
    name: "Beef Asparagus (Seasonal)",
    price: 16.95,
    description: "stir fried beef, asparagus",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Hunan Beef",
    price: 16.95,
    description: "fried beef, hot chilis, bell peppers, onions, carrots",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787852/China%20Center/Food%20Items/Beef/hunan_bf_naudfn.jpg",
  },
  {
    name: "Green Bean Beef",
    price: 16.95,
    description: "stir fried beef, green beans",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },
  // Chicken
  {
    name: "Garlic Chicken",
    price: 12.95,
    description:
      "stir fried chicken, hot chilis, garlic, zucchini strips, broccoli, carrots",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366895/China%20Center/Food%20Items/Chicken/Garlic_CH_qgf7th.jpg",
  },
  {
    name: "Kung Pao Chicken",
    price: 12.95,
    description:
      "stir fried chicken, hot chilis, celery, onion, green bell peppers, carrots, peanuts",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366891/China%20Center/Food%20Items/Chicken/Ch_KungPo_wfj1kd.jpg",
  },
  {
    name: "Chicken with Broccoli",
    price: 12.95,
    description: "stir fried chicken, broccoli",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Sweet & Sour Chicken",
    price: 12.95,
    description: "crispy fried chicken, sweet & sour sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1678220877/China%20Center/Food%20Items/Chicken/ss_chicken_s5g9kt.jpg",
  },
  {
    name: "Cashew Chicken",
    price: 12.95,
    description: "stir fried chicken, veggies, cashews",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787258/China%20Center/Food%20Items/Chicken/cashew_ch_snvy2a.jpg",
  },
  {
    name: "Almond Chicken",
    price: 12.95,
    description: "stir fried chicken, veggies, almonds",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Chicken with Assorted Vegetables",
    price: 12.95,
    description: "stir fried chicken, assorted vegetables",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679016121/China%20Center/Food%20Items/Chicken/ch_veg_vtlu0e.jpg",
  },
  {
    name: "Chicken with Chinese Green",
    price: 12.95,
    description: "stir fried chicken, baby bok choy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Curry Chicken",
    price: 12.95,
    description: "stir fried chicken, veggies, curry sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677990668/China%20Center/Food%20Items/Chicken/curry_chicken_nplkok.jpg",
  },
  {
    name: "Lemon Chicken",
    price: 12.95,
    description: "crispy fried chicken, lemon orange sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Sesame Chicken",
    price: 12.95,
    description: "crispy fried chicken,orange sauce, sesame seeds",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679016288/China%20Center/Food%20Items/Chicken/sesame_ch_nlcuc0.jpg",
  },
  {
    name: "Orange Chicken",
    price: 12.95,
    description: "crispy fried chicken, orange sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366925/China%20Center/Food%20Items/Chicken/Orange_Ch_ki0xuj.jpg",
  },
  {
    name: "Szechuan Chicken",
    price: 12.95,
    description:
      "stir fried chicken, hot chilis, cabbage, bamboo shoots, cloud ear mushrooms",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Pineapple Chicken",
    price: 12.95,
    description: "crispy fried chicken, pineapple orange sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677990702/China%20Center/Food%20Items/Chicken/pineapple_ch_de74wj.jpg",
  },
  {
    name: "General's Chicken",
    price: 14.95,
    description: "crispy fried chicken, hot chilis, broccoli, general sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366906/China%20Center/Food%20Items/Chicken/General_CH_iyxq3m.jpg",
  },
  {
    name: "Chicken with Bitter Melon",
    price: 14.95,
    description: "stir fried chicken, bittermelon",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Chicken with Fresh Mushroom",
    price: 14.95,
    description: "stir fried chicken, mushroom",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Green Bean Chicken",
    price: 14.95,
    description: "stir fried chicken, green beans",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Mandarin House Chicken",
    price: 16.95,
    description: "crispy fried bone-in chicken wings, mandarin house sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366916/China%20Center/Food%20Items/Chicken/Mandarin_House_CH_wulav5.jpg",
  },
  {
    name: "Black Mushroom Chicken",
    price: 16.95,
    description: "stir fried chicken, shitake mushrooms",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366886/China%20Center/Food%20Items/Chicken/BMushroom_Ch_e0xmsi.jpg",
  },
  {
    name: "Chicken with Snow Peas",
    price: 16.95,
    description: "stir fried chicken, snow peas",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl: "",
  },
  // Vegetarian
  {
    name: "Kung Pao Tofu",
    price: 12.95,
    description: "tofu - choice of soft or fried, veggies, peanuts",
    isSpicy: true,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 7,
    imageUrl: "",
  },
  {
    name: "Mixed Vegetables",
    price: 12.95,
    description: "stir fried vegetables",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 7,
    imageUrl: "",
  },
  {
    name: "Steamed Broccoli",
    price: 12.95,
    description: "broccoli",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 7,
    imageUrl: "",
  },
  {
    name: "Fried Tofu",
    price: 12.95,
    description: "fried tofu",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 7,
    imageUrl: "",
  },
  {
    name: "Garlic Eggplant with Tofu",
    price: 12.95,
    description: "fried eggplant, fried tofu",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 7,
    imageUrl: "",
  },
  // Chop Suey & Egg Foo Yung

  {
    name: "Egg Foo Yung",
    price: 12.95,
    description:
      "egg patties, cabbage, beansprouts, choice of protein, asian gravy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 8,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679016076/China%20Center/Food%20Items/Chop%20Suey%20Egg%20FY/ch_egg_foo_yung_z5uwhs.jpg",
  },

  {
    name: "Ho Su Tofu",
    price: 15.95,
    description:
      "tofu - choice of soft or fried, shitake mushrooms, barbecue pork, shrimp, bok choy, beansprouts",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 8,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787242/China%20Center/Food%20Items/Chop%20Suey%20Egg%20FY/ho_su_tofu_bdpyel.jpg",
  },
  {
    name: "Chop Suey",
    price: 15.95,
    description:
      "stir fried beansprouts, assorted vegetables, choice of protein",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 8,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787156/China%20Center/Food%20Items/Chop%20Suey%20Egg%20FY/special_cs_saibrj.jpg",
  },

  // Pork
  {
    name: "Sweet & Sour Pork",
    price: 12.95,
    description: "crispy fried pork, sweet & sour sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787104/China%20Center/Food%20Items/Pork/ss_p_jcx3c2.jpg",
  },
  {
    name: "Pork with Beansprouts",
    price: 12.95,
    description: "stir fried pork, beansprouts",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Pork with Tofu",
    price: 12.95,
    description: "stir fried pork, tofu - choice of soft or fried",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367078/China%20Center/Food%20Items/Pork/Pork_Tofu_cbpujb.jpg",
  },
  {
    name: "Spareribs with Black Bean Sauce",
    price: 14.95,
    description:
      "stir fried spareribs, onions, green bell peppers, black bean sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367071/China%20Center/Food%20Items/Pork/BBean_Sparewib_ofiqok.jpg",
  },
  {
    name: "Pork with Chinese Green",
    price: 12.95,
    description: "stir fried pork, baby bok choy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Ma Pao Tofu",
    price: 12.95,
    description: "steamed tofu, pork, green onions",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1678137735/China%20Center/Food%20Items/Pork/mapo_tofu_m7zabm.jpg",
  },
  {
    name: "Garlic Eggplant with Pork",
    price: 12.95,
    description: "fried eggplant, pork, garlic",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Pork Bittermelon",
    price: 14.95,
    description: "stir fried pork, bittermelon",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Garlic Pork",
    price: 12.95,
    description: "stir fried pork, hot chilis, veggies, garlic",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Chun King Pork",
    price: 12.95,
    description: "stir fried pork, hot chilis, cabbage, bamboo shoots",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1678220841/China%20Center/Food%20Items/Pork/chun_king_pork_zmkczv.jpg",
  },
  {
    name: "Szechuan Pork",
    price: 12.95,
    description: "stir fried pork, cabbage, bamboo shoots, wood ear mushrooms",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Barbeque Pork with Broccoli",
    price: 12.95,
    description: "stir fried barbeque pork, broccoli",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl: "",
  },
  // From The Sea

  {
    name: "Shrimp Vegetable",
    price: 15.95,
    description: "stir fried shrimp, veggies",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366971/China%20Center/Food%20Items/From%20The%20Sea/Shr_Veg_c9dhvy.jpg",
  },
  {
    name: "Kung Pao Seafood",
    price: 16.95,
    description:
      "stir fried squid, shrimp, fish fillet, hot chilis, veggies, peanuts",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1678137818/China%20Center/Food%20Items/From%20The%20Sea/kp_seafood_cowy7d.jpg",
  },
  {
    name: "Shrimp with Chinese Green",
    price: 15.95,
    description: "stir fried shrimp, baby bok choy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Garlic Shrimp",
    price: 15.95,
    description: "stir fried shrimp, hot chilis, veggies, garlic",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366960/China%20Center/Food%20Items/From%20The%20Sea/Garlic_Shrimp_go2tgz.jpg",
  },
  {
    name: "Shrimp with Lobster Sauce",
    price: 15.95,
    description: "stir fried shrimp, veggies, lobster sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Szechuan Shrimp",
    price: 15.95,
    description: "stir fried shrimp, hot chilis, cabbage, wood ear mushroom",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679015680/China%20Center/Food%20Items/From%20The%20Sea/sze_shr_p91gmc.jpg",
  },
  {
    name: "Sweet & Sour Shrimp",
    price: 15.95,
    description: "crispy fried shrimp, sweet & sour sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Curry Shrimp",
    price: 15.95,
    description: "stir fried shrimp, vegetables, curry sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Shrimp with Black Bean Sauce",
    price: 15.95,
    description: "stir fried shrimp, veggies, black bean sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366955/China%20Center/Food%20Items/From%20The%20Sea/BBean_Shrimp_bvqpl2.jpg",
  },
  {
    name: "Kung Pao Fish Fillet",
    price: 15.95,
    description: "stir fried fish fillet, hot chilis, veggies, peanuts",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Fish Fillet with Vegetables",
    price: 15.95,
    description: "stir fried fish fillet, veggies",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Cashew Shrimp",
    price: 15.95,
    description: "stir fried shrimp, veggies, cashews",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Pan Fried Shrimp",
    price: 17.95,
    description:
      "crispy fried whole shelled shrimp, hot chilis, serrano peppers, ginger, green onions, garlic",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366965/China%20Center/Food%20Items/From%20The%20Sea/Pan_Fried_Shrimp_feozch.jpg",
  },
  {
    name: "Shrimp with Green Bean",
    price: 17.95,
    description: "stir fried shrimp, green beans",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Shrimp with Snow Peas",
    price: 17.95,
    description: "stir fried shrimp, snow peas",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Shrimp Asparagus",
    price: 17.95,
    description: "stir fried shrimp, asparagus",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677460137/China%20Center/Food%20Items/From%20The%20Sea/shr_asp_m9bqec.jpg",
  },
  {
    name: "Seafood Vegetable",
    price: 17.95,
    description: "stir fried shrimp, squid, veggies",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Walnut Shrimp",
    price: 17.95,
    description: "crispy fried shrimp, broccoli, honey, walnuts",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787142/China%20Center/Food%20Items/From%20The%20Sea/walnut_shr_lh2ads.jpg",
  },
  // Combination Plates
  {
    name: "Combo Plate A",
    price: 13.95,
    description:
      "chicken chow mein, pork fried rice, sweet & sour pork, fried prawns",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 11,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677990415/China%20Center/Food%20Items/Combo%20Plates/A_Edited_md7or1.png",
  },
  {
    name: "Combo Plate B",
    price: 14.95,
    description: "vegetable beef, pork fried rice, egg roll, fried prawns",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 11,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677990784/China%20Center/Food%20Items/Combo%20Plates/b_edited_ja5mzg.png",
  },
  {
    name: "Combo Plate C",
    price: 14.95,
    description:
      "beef broccoli, pork fried rice, sweet & sour pork, fried prawns",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 11,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677990429/China%20Center/Food%20Items/Combo%20Plates/C_Edited_cmlmbo.jpg",
  },
  {
    name: "Combo Plate D",
    price: 14.95,
    description:
      "almond chicken, pork fried rice, sweet & sour pork, fried prawns",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 11,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677990434/China%20Center/Food%20Items/Combo%20Plates/D_Edited_mfjkbd.jpg",
  },
  // Chinese Family Dinner for 2 or more
  {
    name: "No.1 Family Dinner",
    price: 15.95,
    description: "portion size increases with each additional persons",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 12,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677990944/China%20Center/Food%20Items/Family%20Dinner/Family_Dinner_1_rczihz.png",
  },
  {
    name: "No.2 Family Dinner",
    price: 15.95,
    description: "portion size increases with each additional persons",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 12,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677990944/China%20Center/Food%20Items/Family%20Dinner/family_dinner_2_s5cm7w.png",
  },
  {
    name: "No.3 Family Dinner",
    price: 16.95,
    description: "portion size increases with each additional persons",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 12,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677990944/China%20Center/Food%20Items/Family%20Dinner/family_dinner_3_xstvat.png",
  },
  // Lunch Special
  {
    name: "Beef Oyster Sauce (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Sweet & Sour Pork (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Almond Chicken (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Beef Broccoli (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679015589/China%20Center/Food%20Items/Lunch/broc_bf_lunch_gw0i6t.jpg",
  },
  {
    name: "Beef Green Pepper (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Curry Chicken (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Chicken or Pork Chow Mein (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679016099/China%20Center/Food%20Items/Lunch/ch_lunch_zxks33.jpg",
  },
  {
    name: "Chicken Broccoli (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1678220806/China%20Center/Food%20Items/Chicken/ch_broccoli_ri3kwa.jpg",
  },
  {
    name: "Kung Pao Chicken or Beef (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Garlic Chicken (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Sweet & Sour Chicken (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Chop Suey (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679015693/China%20Center/Food%20Items/Lunch/shr_cs_j5skzv.jpg",
  },
  {
    name: "Shrimp Vegetable (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Garlic Shrimp (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679015648/China%20Center/Food%20Items/Lunch/gar_shr_lunch_ghrqcm.jpg",
  },
  {
    name: "Mongolian Beef (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Seafood Vegetable (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Fish Fillet Vegetable (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679015612/China%20Center/Food%20Items/Lunch/fish_veg_lunch_noylj1.jpg",
  },
  {
    name: "General Chicken (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679015601/China%20Center/Food%20Items/Lunch/gen_ch_lunch_gfun4c.jpg",
  },
  {
    name: "Kung Pao Fish Fillet (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Orange Chicken (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Glass Wine",
    price: 8,
    description: "chardonnay",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Domestic Beer",
    price: 5,
    description: "Budlight, Coors",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Imported Beer",
    price: 6,
    description: "Modelo, Corona, Tsingtao",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Hot Tea",
    price: 2.5,
    description: "oolong",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Ice Tea",
    price: 2.5,
    description: "cold oolong tea",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Soft Drink",
    price: 2.5,
    description:
      "Coke, Sprite, Sunkist, Dr.Pepper, Pepsi, Diet Coke, Diet Dr.Pepper, Pink Lemonade, Yellow Lemonade, Root Beer",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Orange or Apple Juice",
    price: 3.95,
    description: "individually bottled",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 14,
    imageUrl: "",
  },
];

const Categories = [
  {
    id: 1,
    name: "Appetizers",
  },
  {
    id: 2,
    name: "Soups",
  },
  {
    id: 3,
    name: "Fried Rice",
  },
  {
    id: 4,
    name: "Chow Mein",
  },
  {
    id: 5,
    name: "Beef",
  },
  {
    id: 6,
    name: "Chicken",
  },
  {
    id: 7,
    name: "Vegetarian",
  },
  {
    id: 8,
    name: "Chop Suey & Egg Foo Yung",
  },
  {
    id: 9,
    name: "Pork",
  },
  {
    id: 10,
    name: "From The Sea",
  },
  {
    id: 11,
    name: "Combo Plate",
  },
  {
    id: 12,
    name: "Family Dinner",
  },
  {
    id: 13,
    name: "Lunch Special",
  },
  {
    id: 14,
    name: "Drinks",
  },
];

module.exports = {
  Items,
  Categories,
};
