const Items = [
  //Appetizers
  {
    name: "Egg Rolls",
    price: 6.0,
    description: "Crispy fried egg rolls, served with a sweet & sour dip",
    isSpicy: false,
    isVegan: false,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366657/China%20Center/Food%20Items/Apps/Eggroll_yj9gsj.jpg",
  },
  {
    name: "Fried Wonton",
    price: 7.5,
    description: "Crispy fried wonton skins, served with a sweet & sour dip",
    isSpicy: false,
    isVegan: false,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366674/China%20Center/Food%20Items/Apps/Fried_Wtn_ngrl96.jpg",
  },
  {
    name: "Potstickers",
    price: 10.5,
    description:
      "Savory Chinese potstickers, served with a chili & vinegar dip",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366679/China%20Center/Food%20Items/Apps/Pot_Stickers_at8ss2.jpg",
  },
  {
    name: "Fried Prawns",
    price: 10.5,
    description: "Crispy fried prawns, served with a sweet & sour dip",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366668/China%20Center/Food%20Items/Apps/Fried_Prawns_uwwgts.jpg",
  },
  {
    name: "Barbecue Pork",
    price: 10.5,
    description: "In our house marinade",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366496/China%20Center/Food%20Items/Apps/BBQ_Pork_y3lrin.jpg",
  },
  {
    name: "Fried Chicken Wings",
    price: 10.95,
    description: "Fried chicken wings, served with a sweet & sour dip",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677459944/China%20Center/Food%20Items/Apps/fr_ch_wing_bkwpz5.jpg",
  },
  {
    name: "Fried Squid",
    price: 10.95,
    description: "Tender fried squid, served with a sweet & sour dip",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 1,
    imageUrl: "",
  },
  {
    name: "Cream Cheese Crab Puff",
    price: 10.95,
    description:
      "Crispy wonton shells filled with imitation crab meat and cream cheese, served with a sweet & sour dip",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: false,
    isGlutenFree: false,
    category_id: 1,
    imageUrl: "",
  },
  {
    name: "Assorted Appetizer (For 2)",
    price: 22.5,
    description:
      "An assortment of all our appetizers put together and shrimp chips, served with a sweet & sour dip",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: false,
    isGlutenFree: false,
    category_id: 1,
    imageUrl: "",
  },
  {
    name: "French Fries",
    price: 6.0,
    description: "Crispy fried french fries",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 1,
    imageUrl: "",
  },
  {
    name: "Shrimp Chips",
    price: 6.0,
    description:
      "Colorful fried chips made of a mixture of dried shrimp and tapioca flour",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366685/China%20Center/Food%20Items/Apps/Shrimp_Chips_hpj1tj.jpg",
  },
  // Wonton Noodle Soup
  {
    name: "Hot & Sour Soup",
    price: 10.95,
    description:
      "Pork, tofu, bamboo shoot, wood ear mushroom and creamy egg mixture in a hot & sour broth",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787814/China%20Center/Food%20Items/Soup/hot_n_sour_rzn0uh.jpg",
  },
  {
    name: "Seaweed Soup",
    price: 10.95,
    description: "Chicken, seaweed, and creamy egg mixture in an umami broth",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366014/China%20Center/Food%20Items/Soup/Seaweed_Sp_fu1u0b.jpg",
  },
  {
    name: "Egg Flower Soup",
    price: 10.95,
    description:
      "Chicken, tofu, celery, mushroom and creamy egg mixture in an umami broth",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677365997/China%20Center/Food%20Items/Soup/Eggflower_Soup_l4iaxx.jpg",
  },
  {
    name: "Corn Chicken Soup",
    price: 10.95,
    description: "Chicken, corn, and creamy egg mixture in an umami broth",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    category_id: 2,
    imageUrl: "",
  },
  {
    name: "Plain Wonton Soup (L)",
    price: 10.95,
    description: "Large sized pork filled wontons in an umami broth",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 2,
    imageUrl: "",
  },
  {
    name: "Plain Wonton Soup (S)",
    price: 3.0,
    description: "Small sized pork filled wontons in an umami broth",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366031/China%20Center/Food%20Items/Soup/Small_Wtn_rd4byo.jpg",
  },
  {
    name: "Shrimp Sizzling Rice Soup",
    price: 12.95,
    description:
      "Crispy sizzling rice on top of shrimp, mushroom, bamboo shoot, water chestnut in an umami broth",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366026/China%20Center/Food%20Items/Soup/Siz_Sp_cvfxmq.jpg",
  },
  {
    name: "Pork Wonton and/or Noodle Soup",
    price: 12.95,
    description:
      "Pork filled wontons with pork, bok choy, shitake mushrooms, bamboo shoot, water chestnut in an umami broth. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 2,
    imageUrl: "",
  },
  {
    name: "Chicken Wonton and/or Noodle Soup",
    price: 12.95,
    description:
      "Pork filled wontons with chicken, bok choy, shitake mushrooms, bamboo shoot, water chestnut in an umami broth. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677365944/China%20Center/Food%20Items/Soup/Ch_Wtn_Ndl_vyucx0.jpg",
  },
  {
    name: "Beef Wonton and/or Noodle Soup",
    price: 12.95,
    description:
      "Pork filled wontons with beef, bok choy, shitake mushrooms, bamboo shoot, water chestnut in an umami broth. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787275/China%20Center/Food%20Items/Soup/bf_wtn_mtjyy2.jpg",
  },
  {
    name: "Combo Sizzling Rice Soup",
    price: 13.95,
    description:
      "Crispy sizzling rice on top of chicken, pork, shrimp, mushroom, bamboo shoot, water chestnut in an umami broth",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366026/China%20Center/Food%20Items/Soup/Siz_Sp_cvfxmq.jpg",
  },
  {
    name: "Wor Wonton and/or Noodle Soup",
    price: 13.95,
    description:
      "Pork filled wontons with chicken, pork, shrimp, bok choy, shitake mushrooms, bamboo shoot, water chestnut in an umami broth. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366042/China%20Center/Food%20Items/Soup/WWT_lqolqa.jpg",
  },
  {
    name: "Shrimp Wonton and/or Noodle Soup",
    price: 13.95,
    description:
      "Pork filled wontons with shrimp, bok choy, shitake mushrooms, bamboo shoot, water chestnut in an umami broth. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366020/China%20Center/Food%20Items/Soup/Shr_Wtn_jq83ub.jpg",
  },
  {
    name: "Seafood Sizzling Rice Soup",
    price: 14.95,
    description:
      "Crispy sizzling rice on top of imitation crab meat, fish, shrimp, mushroom, bamboo shoot, water chestnut in an umami broth",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366026/China%20Center/Food%20Items/Soup/Siz_Sp_cvfxmq.jpg",
  },
  // Fried Rice
  {
    name: "Steamed Rice (S)",
    price: 2.0,
    description: "Small steamed rice",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: true,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677460033/China%20Center/Food%20Items/Fried%20Rice/sm_rice_txyd3i.jpg",
  },
  {
    name: "Steamed Rice (L)",
    price: 3.0,
    description: "Large steamed rice",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: true,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677460030/China%20Center/Food%20Items/Fried%20Rice/large_rice_gkqbqy.jpg",
  },
  {
    name: "Chicken Fried Rice",
    price: 9.5,
    description: "Fried rice with egg, chicken, & green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677459821/China%20Center/Food%20Items/Fried%20Rice/ch_fried_rice_ripmsg.jpg",
  },
  {
    name: "Pork Fried Rice",
    price: 9.5,
    description: "Fried rice with egg, pork, peas & carrots",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367115/China%20Center/Food%20Items/Fried%20Rice/P_FR_z1c6i8.jpg",
  },
  {
    name: "Beef Fried Rice",
    price: 9.5,
    description: "Fried rice with egg, beef, & green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 3,
    imageUrl: "",
  },
  {
    name: "Vegetable Fried Rice",
    price: 9.5,
    description:
      "Fried rice with egg, beansprouts, peas, carrots, & green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367107/China%20Center/Food%20Items/Fried%20Rice/Fried_Rice_VEG_f9kcpl.jpg",
  },
  {
    name: "Special Fried Rice",
    price: 10.5,
    description: "Fried rice with egg, pork, chicken, shrimp, peas & carrots",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367102/China%20Center/Food%20Items/Fried%20Rice/Fried_Rice_SP_t1fh9g.jpg",
  },
  {
    name: "Shrimp Fried Rice",
    price: 10.5,
    description: "Fried rice with egg, shrimp, & green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787088/China%20Center/Food%20Items/Fried%20Rice/shr_fr_gqnuui.jpg",
  },

  //Chow Mein
  {
    name: "Plain Chow Mein",
    price: 9.95,
    description: "Stir fried noodles with beansprouts & cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787173/China%20Center/Food%20Items/Noods/plain_cm_bie4u8.jpg",
  },
  {
    name: "Chicken Chow Mein",
    price: 10.95,
    description: "Stir fried noodles with chicken, beansprouts, & cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl: "",
  },
  {
    name: "Chicken Almond Chow Mein",
    price: 10.95,
    description:
      "Stir fried noodles with chicken, almonds, beansprouts, & cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367027/China%20Center/Food%20Items/Noods/Ch_Almond_CM_yczh06.jpg",
  },
  {
    name: "Pork Chow Mein",
    price: 10.95,
    description: "Stir fried noodles with pork, beansprouts, & cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl: "",
  },
  {
    name: "Vegetable Chow Mein",
    price: 10.95,
    description:
      "Stir fried noodles with broccoli, carrots, bokchoy, beansprouts, & cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787123/China%20Center/Food%20Items/Noods/veg_cm_sooolf.jpg",
  },
  {
    name: "Special Chow Mein",
    price: 11.5,
    description:
      "Stir fried noodles with pork, chicken, shrimp, beansprouts, cabbage & snow peas",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367046/China%20Center/Food%20Items/Noods/SP_CM_wwh9hi.jpg",
  },
  {
    name: "Shrimp Chow Mein",
    price: 11.5,
    description: "Stir fried noodles with shrimp, beansprouts, & cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367040/China%20Center/Food%20Items/Noods/Shr_Cm_d0cldk.jpg",
  },
  {
    name: "Beef Chow Mein",
    price: 11.5,
    description: "Stir fried noodles with beef, beansprouts, & cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367024/China%20Center/Food%20Items/Noods/Bf_CM_cyh005.jpg",
  },
  {
    name: "Beef Tomato Chow Mein",
    price: 11.5,
    description:
      "Stir fried noodles with beef, green bell pepper, onion, beansprouts, cabbage, & tomato sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl: "",
  },
  {
    name: "B.B.Q. Pork Chow Mein",
    price: 10.95,
    description:
      "Stir fried noodles with barbeque pork, beansprouts, & cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl: "",
  },
  {
    name: "Pansit",
    price: 11.5,
    description:
      "Rice stick noodles stir fried with egg, beansprouts & your choice of protein",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367032/China%20Center/Food%20Items/Noods/CH_Pansit_yohwdi.jpg",
  },
  {
    name: "Beef Chow Fun",
    price: 12.95,
    description:
      "Rice stick noodle stir fried with beef, beansprouts, & green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367018/China%20Center/Food%20Items/Noods/Bf_Chowfun_zgip65.jpg",
  },
  {
    name: "Seafood Chow Mein",
    price: 12.95,
    description:
      "Stir fried noodles with squid, shrimp, beansprouts, cabbage, & snow peas",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl: "",
  },
  {
    name: "Shrimp Chow Fun",
    price: 13.95,
    description:
      "Rice stick noodle stir fried with shrimp, beansprouts, & green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl: "",
  },
  {
    name: "Singapore Chow Mein",
    price: 13.95,
    description:
      "Rice stick noodle stir fried with choice of protein, curry powder, & beansprouts",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787893/China%20Center/Food%20Items/Noods/singapore_chow_mein_mkpp8x.jpg",
  },
  {
    name: "House Pan Fried Noodle Sizzling Plate",
    price: 16.5,
    description:
      "Crispy pan fried noodles under assorted combination of meats & veggies",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677459991/China%20Center/Food%20Items/Noods/hot_plate_trw5wn.jpg",
  },
  //Beef
  {
    name: "Beef Broccoli",
    price: 13.95,
    description: "Stir fried beef & broccoli in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366827/China%20Center/Food%20Items/Beef/Brocc_BF_g7kzda.jpg",
  },
  {
    name: "Ginger Beef",
    price: 14.95,
    description: "Stir fried beef, ginger, & green onion in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef with Oyster Sauce",
    price: 14.95,
    description:
      " Stir fried beef with oyster sauce and a variety of vegetables",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef with Tomato",
    price: 14.95,
    description: "Stir fried beef with tomatoes in a tomato sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef with Beansprouts",
    price: 14.95,
    description: "Stir fried beef with beansprouts in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef with Beansprouts",
    price: 14.95,
    description: "Stir fried beef with beansprouts in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef with Chinese Greens",
    price: 14.95,
    description: "Stir fried beef with baby bok choy in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef with Tofu",
    price: 14.95,
    description: "Stir fried beef with tofu in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef with Cashew Nut",
    price: 14.95,
    description: "Stir fried beef with cashews & vegetables in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Green Pepper Beef",
    price: 14.95,
    description: "Stir fried beef with green bell peppers in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef with Assorted Vegetables",
    price: 14.95,
    description: "Stir fried beef with assorted vegetables in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef Bittermelon",
    price: 14.95,
    description: "Stir fried beef with bittermelon in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Curry Beef",
    price: 14.95,
    description:
      "Stir fried beef with assortment of vegetables in a curry sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Kung Pao Beef",
    price: 14.95,
    description:
      "Stir fried beef with hot chilis & assortment of vegetables in a spicy sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787186/China%20Center/Food%20Items/Beef/kp_bf_vvfu4m.jpg",
  },
  {
    name: "Szechaun Beef",
    price: 14.95,
    description:
      "Stir fried beef with hot chilis, cabbage, & cloud ear mushrooms in a spicy sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Mongolian Beef",
    price: 16.95,
    description:
      "Stir fried beef with hot chilis, mushrooms, bamboo shoots & green onions",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677460071/China%20Center/Food%20Items/Beef/mong_bf_wcgrux.jpg",
  },
  {
    name: "Beef Asparagus (Seasonal)",
    price: 16.95,
    description: "Stir fried beef with asparagus",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Hunan Beef",
    price: 16.95,
    description: "Fried beef with a spicy sauce and assorted vegetables",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787852/China%20Center/Food%20Items/Beef/hunan_bf_naudfn.jpg",
  },
  {
    name: "Green Bean Beef",
    price: 16.95,
    description: "Stir fried beef with green beans",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 5,
    imageUrl: "",
  },
  // Chicken
  {
    name: "Garlic Chicken",
    price: 12.95,
    description:
      "Stir fried chicken with hot chilis, zucchini strips, broccoli, & carrots in a garlic sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366895/China%20Center/Food%20Items/Chicken/Garlic_CH_qgf7th.jpg",
  },
  {
    name: "Kung Pao Chicken",
    price: 12.95,
    description:
      "Stir fried chicken with hot chilis, celery, onion, green bell peppers, & carrots in a spicy sauce topped with peanuts",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366891/China%20Center/Food%20Items/Chicken/Ch_KungPo_wfj1kd.jpg",
  },
  {
    name: "Chicken with Broccoli",
    price: 12.95,
    description: "Stir fried chicken with broccoli in a rich sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Sweet & Sour Chicken",
    price: 12.95,
    description: "Crispy fried chicken in a sweet & sour sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Cashew Chicken",
    price: 12.95,
    description:
      "Stir fried chicken with a medley of vegetables topped with cashew nuts",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787258/China%20Center/Food%20Items/Chicken/cashew_ch_snvy2a.jpg",
  },
  {
    name: "Almond Chicken",
    price: 12.95,
    description:
      "Stir fried chicken with a medley of vegetables topped with almonds",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Chicken with Assorted Vegetables",
    price: 12.95,
    description: "Stir fried chicken with an assortment of vegetables",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Chicken with Chinese Green",
    price: 12.95,
    description: "Stir fried chicken with bok choy in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Curry Chicken",
    price: 12.95,
    description:
      "Stir fried chicken with a variety of vegetables in a curry sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Lemon Chicken",
    price: 12.95,
    description: "Crispy fried chicken with our lemon sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Orange Chicken",
    price: 12.95,
    description: "Crispy fried chicken with our orange sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366925/China%20Center/Food%20Items/Chicken/Orange_Ch_ki0xuj.jpg",
  },
  {
    name: "Szechuan Chicken",
    price: 12.95,
    description:
      "Stir fried chicken with hot chilis, cabbage, bamboo shoots, & cloud ear mushrooms in a chili sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Pineapple Chicken",
    price: 12.95,
    description: "Crispy fried chicken with our pineapple sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "General's Chicken",
    price: 14.95,
    description: "Crispy fried chicken with broccoli our spicy general sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366906/China%20Center/Food%20Items/Chicken/General_CH_iyxq3m.jpg",
  },
  {
    name: "Chicken with Bitter Melon",
    price: 14.95,
    description: "Stir fried chicken with bitter melon in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Chicken with Fresh Mushroom",
    price: 14.95,
    description: "Stir fried chicken with mushrooms in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Green Bean Chicken",
    price: 14.95,
    description: "Stir fried chicken with green beans in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Mandarin House Chicken",
    price: 16.95,
    description:
      "Crispy fried chicken wings covered in our mandarin house sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366916/China%20Center/Food%20Items/Chicken/Mandarin_House_CH_wulav5.jpg",
  },
  {
    name: "Black Mushroom Chicken",
    price: 16.95,
    description: "Stir fried chicken with shitake mushrooms in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366886/China%20Center/Food%20Items/Chicken/BMushroom_Ch_e0xmsi.jpg",
  },
  {
    name: "Chicken with Snow Peas",
    price: 16.95,
    description: "Stir fried chicken with chinese snow peas in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 6,
    imageUrl: "",
  },
  // Vegetarian
  {
    name: "Kung Pao Tofu",
    price: 12.95,
    description:
      "Choice of soft or deep fried tofu mixed with a medley of vegetables in a rich spicy sauce topped with peanuts",
    isSpicy: true,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 7,
    imageUrl: "",
  },
  {
    name: "Mixed Vegetables",
    price: 12.95,
    description: "Stir fried vegetables in a rich clear sauce",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 7,
    imageUrl: "",
  },
  {
    name: "Steamed Broccoli",
    price: 12.95,
    description: "Broccoli in a rich sauce",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 7,
    imageUrl: "",
  },
  {
    name: "Fried Tofu",
    price: 12.95,
    description: "Fried tofu in a rich sauce",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 7,
    imageUrl: "",
  },
  {
    name: "Garlic Eggplant with Tofu",
    price: 12.95,
    description: "Fried eggplant with friend tofu in a rich garlic sauce",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 7,
    imageUrl: "",
  },
  // Chop Suey & Egg Foo Yung
  {
    name: "Chicken Chop Suey",
    price: 12.95,
    description:
      "Stir fried chicken with beansprouts and other vegetables in a rich clear sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 8,
    imageUrl: "",
  },
  {
    name: "Beef Chop Suey",
    price: 12.95,
    description:
      "Stir fried beef with beansprouts and other vegetables in a rich clear sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 8,
    imageUrl: "",
  },
  {
    name: "Pork Chop Suey",
    price: 12.95,
    description:
      "Stir fried pork with beansprouts and other vegetables in a rich clear sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 8,
    imageUrl: "",
  },
  {
    name: "Chicken Egg Foo Yung",
    price: 12.95,
    description:
      "Egg patties filled with chicken, cabbage, & beansprouts in an asian style gravy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 8,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677459915/China%20Center/Food%20Items/Chop%20Suey%20Egg%20FY/egg_foo_yung_jpfriv.jpg",
  },
  {
    name: "Beef Egg Foo Yung",
    price: 12.95,
    description:
      "Egg patties filled with beef, cabbage, & beansprouts in an asian style gravy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 8,
    imageUrl: "",
  },
  {
    name: "Pork Egg Foo Yung",
    price: 12.95,
    description:
      "Egg patties filled with barbecue pork, cabbage, & beansprouts in an asian style gravy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 8,
    imageUrl: "",
  },
  {
    name: "Vegetable Egg Foo Yung",
    price: 12.95,
    description:
      "Egg patties filled with peas, carrots, cabbage, & beansprouts in an asian style gravy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 8,
    imageUrl: "",
  },
  {
    name: "Special Egg Foo Yung",
    price: 13.95,
    description:
      "Egg patties filled with chicken, shrimp, barbecue pork, cabbage, & beansprouts in an asian style gravy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 8,
    imageUrl: "",
  },
  {
    name: "Shrimp Egg Foo Yung",
    price: 13.95,
    description:
      "Egg patties filled with shrimp, cabbage, & beansprouts in an asian style gravy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 8,
    imageUrl: "",
  },
  {
    name: "Ho Su Tofu",
    price: 15.95,
    description:
      "Soft or friend tofu mixed with shitake mushrooms, barbecue pork, shrimp, bok choy, & beansprouts in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 8,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787242/China%20Center/Food%20Items/Chop%20Suey%20Egg%20FY/ho_su_tofu_bdpyel.jpg",
  },
  {
    name: "Special Chop Suey",
    price: 15.95,
    description:
      "Stir fried chicken, shrimp, and pork with beansprouts and other vegetables in a rich clear sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 8,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787156/China%20Center/Food%20Items/Chop%20Suey%20Egg%20FY/special_cs_saibrj.jpg",
  },
  {
    name: "Shrimp Chop Suey",
    price: 15.95,
    description:
      "Stir fried shrimp with beansprouts and other vegetables in a rich clear sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 8,
    imageUrl: "",
  },
  // Pork
  {
    name: "Sweet & Sour Pork",
    price: 12.95,
    description: "Crispy fried pork in a sweet & sour sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787104/China%20Center/Food%20Items/Pork/ss_p_jcx3c2.jpg",
  },
  {
    name: "Pork with Beansprouts",
    price: 12.95,
    description: "Stir fried pork with beansprouts in a rich clear sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Pork with Tofu",
    price: 12.95,
    description: "Stir fried pork with soft or fried tofu in a rich sauce.",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367078/China%20Center/Food%20Items/Pork/Pork_Tofu_cbpujb.jpg",
  },
  {
    name: "Spareribs with Black Bean Sauce",
    price: 14.95,
    description:
      "Stir fried spareribs with onions and green bell peppers in a black bean sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677367071/China%20Center/Food%20Items/Pork/BBean_Sparewib_ofiqok.jpg",
  },
  {
    name: "Pork with Chinese Green",
    price: 12.95,
    description: "Stir fried pork with bok choy in a rich clear sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Ma Pao Tofu",
    price: 12.95,
    description:
      "Steamed tofu with pork and green onions in a rich spicy sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Garlic Eggplant with Pork",
    price: 12.95,
    description: "Fried eggplant with pork in a rich spicy garlic sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Pork Bittermelon",
    price: 14.95,
    description: "Stir fried pork with bitter melon in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Garlic Pork",
    price: 12.95,
    description: "Stir fried pork with vegetables in a rich spicy garlic sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Chun King Pork",
    price: 12.95,
    description:
      "Stir fried pork with cabbage & bamboo shoots in a rich spicy sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Szechaun Pork",
    price: 12.95,
    description:
      "Stir fried pork with cabbage, bamboo shoots, & cloud ear mushrooms in a rich spicy sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Barbeque Pork with Broccoli",
    price: 12.95,
    description: "Stir fried barbeque pork with broccoli in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 9,
    imageUrl: "",
  },
  // From The Sea
  {
    name: "Shrimp Vegetable",
    price: 15.95,
    description: "Stir fried shrimp with vegetables in a rich clear sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366971/China%20Center/Food%20Items/From%20The%20Sea/Shr_Veg_c9dhvy.jpg",
  },
  {
    name: "Shrimp with Chinese Green",
    price: 15.95,
    description: "Stir fried shrimp with bok choy in a rich clear sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Garlic Shrimp",
    price: 15.95,
    description: "Stir fried shrimp with vegetables in a spicy garlic sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366960/China%20Center/Food%20Items/From%20The%20Sea/Garlic_Shrimp_go2tgz.jpg",
  },
  {
    name: "Shrimp with Lobster Sauce",
    price: 15.95,
    description: "Stir fried shrimp with vegetables in a special lobster sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Sweet & Sour Shrimp",
    price: 15.95,
    description: "Crispy fried shrimp in sweet & sour sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Curry Shrimp",
    price: 15.95,
    description: "Stir fried shrimp with vegetables in a curry sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Shrimp with Black Bean Sauce",
    price: 15.95,
    description: "Stir fried shrimp with vegetables in a black bean sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366955/China%20Center/Food%20Items/From%20The%20Sea/BBean_Shrimp_bvqpl2.jpg",
  },
  {
    name: "Kung Pao Fish Fillet",
    price: 15.95,
    description:
      "Stir fried fish fillet with vegetables in a spicy rich sauce with peanuts on top",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Fish Fillet with Vegetables",
    price: 15.95,
    description: "Stir fried fish fillet with vegetables in a rich clear sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Cashew Shrimp",
    price: 15.95,
    description:
      "Stir fried shrimp with vegetables in a rich sauce with cashews on top",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Pan Fried Shrimp",
    price: 17.95,
    description:
      "Crispy fried whole shelled shrimp tossed with hot chilis, serrano peppers, ginger, green onions & garlic",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366965/China%20Center/Food%20Items/From%20The%20Sea/Pan_Fried_Shrimp_feozch.jpg",
  },
  {
    name: "Shrimp with Green Bean",
    price: 17.95,
    description: "Stir fried shrimp with green beans in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Shrimp with Snow Peas",
    price: 17.95,
    description: "Stir fried shrimp with snow peas in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Shrimp Asparagus",
    price: 17.95,
    description: "Stir fried shrimp with asparagus in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677460137/China%20Center/Food%20Items/From%20The%20Sea/shr_asp_m9bqec.jpg",
  },
  {
    name: "Seafood Vegetable",
    price: 17.95,
    description: "Stir fried shrimp & squid with vegetables in a rich sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Walnut Shrimp",
    price: 17.95,
    description:
      "Crispy fried shrimp with broccoli covered in a honey walnut sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677787142/China%20Center/Food%20Items/From%20The%20Sea/walnut_shr_lh2ads.jpg",
  },
  // Combination Plates
  {
    name: "Combo Plate A",
    price: 13.95,
    description:
      "Contains chicken chow mein, pork fried rice, two fried prawns and a saucer of sweet & sour pork",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 11,
    imageUrl: "",
  },
  {
    name: "Combo Plate B",
    price: 14.95,
    description:
      "Contains vegetable beef, pork fried rice, two fried prawns and an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 11,
    imageUrl: "",
  },
  {
    name: "Combo Plate C",
    price: 14.95,
    description:
      "Contains beef broccoli, pork fried rice, two fried prawns and a saucer of sweet & sour pork",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 11,
    imageUrl: "",
  },
  {
    name: "Combo Plate D",
    price: 14.95,
    description:
      "Contains almond chicken, pork fried rice, two fried prawns and a saucer of sweet & sour pork",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 11,
    imageUrl: "",
  },
  // Chinese Family Dinner for 2 or more
  {
    name: "No.1 Family Dinner",
    price: 15.95,
    description:
      "$15.95 per person. No.1 comes with wonton soup, egg rolls, sweet & sour pork, fried wonton, pork fried rice, pork chow mein. For 3 add beef broccoli. For 4 add kung pao chicken.",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 12,
    imageUrl: "",
  },
  {
    name: "No.2 Family Dinner",
    price: 15.95,
    description:
      "$15.95 per person. No.2 comes with wonton soup, egg rolls, fried prawns, sweet & sour pork, pork fried rice, special chow mein. For 3 add almond chicken. For 4 add beef broccoli. ",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 12,
    imageUrl: "",
  },
  {
    name: "No.3 Family Dinner",
    price: 16.95,
    description:
      "$16.95 per person. No.3 comes with wonton soup, fried prawns, fried chicken wings, pork fried rice. Each person may also add an entree of their choice. 1. Chicken Almond Chow Mein. 2. Shrimp Chow Mein. 3. Garlic Chicken. 4. Kung Pao Beef. 5. Broccoli Beef. 6. Orange Chicken.",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 12,
    imageUrl: "",
  },
  // Lunch Special
  {
    name: "Beef Oyster Sauce (Lunch)",
    price: 11.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Sweet & Sour Pork (Lunch)",
    price: 11.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Almond Chicken (Lunch)",
    price: 11.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Beef Broccoli (Lunch)",
    price: 11.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Beef Green Pepper (Lunch)",
    price: 11.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Curry Chicken (Lunch)",
    price: 11.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Chicken or Pork Chow Mein (Lunch)",
    price: 11.95,
    description: "Comes of fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Chicken Broccoli (Lunch)",
    price: 11.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Kung Pao Chicken or Beef (Lunch)",
    price: 11.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Garlic Chicken (Lunch)",
    price: 11.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Sweet & Sour Chicken (Lunch)",
    price: 11.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Beef or Chicken Chop Suey (Lunch)",
    price: 11.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Shrimp Vegetable (Lunch)",
    price: 12.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Garlic Shrimp (Lunch)",
    price: 12.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Mongolian Beef (Lunch)",
    price: 12.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Seafood Vegetable (Lunch)",
    price: 12.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Fish Fillet Vegetable (Lunch)",
    price: 12.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "General Chicken (Lunch)",
    price: 12.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Kung Pao Fish Fillet (Lunch)",
    price: 12.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Orange Chicken (Lunch)",
    price: 12.95,
    description: "Choice of white rice or fried rice & an egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Glass Wine",
    price: 8,
    description: "glass of chardonnay",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Domestic Beer",
    price: 5,
    description: "Budlight, Coors",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Imported Beer",
    price: 6,
    description: "Modelo, Corona, Tsingtao",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Hot Tea",
    price: 2.5,
    description: "Pot of hot oolong tea",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Ice Tea",
    price: 2.5,
    description: "Cold oolong tea",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Soft Drink",
    price: 2.5,
    description:
      "Coke, Sprite, Sunkist, Dr.Pepper, Pepsi, Diet Coke, Diet Dr.Pepper, Pink Lemonade, Yellow Lemonade, Root Beer",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Orange or Apple Juice",
    price: 3.95,
    description: "Individually bottled juices",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    category_id: 14,
    imageUrl: "",
  },
];

const Categories = [
  {
    id: 1,
    name: "Appetizers",
  },
  {
    id: 2,
    name: "Soups",
  },
  {
    id: 3,
    name: "Fried Rice",
  },
  {
    id: 4,
    name: "Chow Mein",
  },
  {
    id: 5,
    name: "Beef",
  },
  {
    id: 6,
    name: "Chicken",
  },
  {
    id: 7,
    name: "Vegetarian",
  },
  {
    id: 8,
    name: "Chop Suey & Egg Foo Yung",
  },
  {
    id: 9,
    name: "Pork",
  },
  {
    id: 10,
    name: "From The Sea",
  },
  {
    id: 11,
    name: "Combo Plate",
  },
  {
    id: 12,
    name: "Family Dinner",
  },
  {
    id: 13,
    name: "Lunch Special",
  },
  {
    id: 14,
    name: "Drinks",
  },
];

module.exports = {
  Items,
  Categories,
};
