const Items = [
  //Appetizers
  {
    name: "Egg Rolls",
    price: 6.0,
    description: "3 crispy eggrolls with cabbage, carrots",
    isSpicy: false,
    isVegan: false,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139226/China%20Center%20Food%20Items/egg_roll_ac1joa.jpg",
  },
  {
    name: "Fried Wonton",
    price: 7.5,
    description: "12 crispy fried wonton skins",
    isSpicy: false,
    isVegan: false,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139226/China%20Center%20Food%20Items/fr_wtn_pfilzs.jpg",
  },
  {
    name: "Potstickers",
    price: 10.5,
    description: "8 potstickers filled with pork, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139230/China%20Center%20Food%20Items/potsticker_kvsemb.jpg",
  },
  {
    name: "Fried Prawns",
    price: 10.5,
    description: "8 fried prawns",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152340/fried_prawns_duhxwm.jpg",
  },
  {
    name: "Barbecue Pork",
    price: 10.5,
    description: "barbeque pork made in house",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152341/bbq_pork_nxk1su.jpg",
  },
  {
    name: "Fried Chicken Wings",
    price: 10.95,
    description: "8 fried chicken wings",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139225/China%20Center%20Food%20Items/ch_wings_q14p0f.jpg",
  },
  {
    name: "Fried Squid",
    price: 10.95,
    description: "8 tender fried squid",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139226/China%20Center%20Food%20Items/fr_squid_bc80kj.jpg",
  },
  {
    name: "Cream Cheese Crab Puff",
    price: 10.95,
    description:
      "10 cream cheese crab puffs with imitation crab, onions, cream cheese",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: false,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139224/China%20Center%20Food%20Items/ccp_hpospu.jpg",
  },
  {
    name: "Assorted Appetizer (For 2)",
    price: 22.5,
    description: "all appetizers in one big serving",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: false,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139223/China%20Center%20Food%20Items/assorted_app_for_2_ax68su.jpg",
  },
  {
    name: "French Fries",
    price: 6.0,
    description: "crispy fried french fries",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1678221243/China%20Center/Food%20Items/Apps/crinkle_cut_fuapzz.jpg",
  },
  {
    name: "Shrimp Chips",
    price: 6.0,
    description:
      "colorful fried prawn chips made with dried shrimp powder, tapioca flour",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 1,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152341/shrimp_chips_n0n6wv.jpg",
  },
  // Wonton Noodle Soup
  {
    name: "Hot & Sour Soup",
    price: 10.95,
    description:
      "pork, tofu, bamboo shoot, wood ear mushroom, creamy egg mixture",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139227/China%20Center%20Food%20Items/hot_n_sour_n6qf7a.jpg",
  },
  {
    name: "Seaweed Soup",
    price: 10.95,
    description:
      "chicken, seaweed, snap peas, mushroom, bamboo shoot, egg mixture",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139228/China%20Center%20Food%20Items/seaweed_sp_jedvbz.jpg",
  },
  {
    name: "Egg Flower Soup",
    price: 10.95,
    description: "chicken, tofu, celery, mushroom, creamy egg mixture",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152340/eggflower_sp_bjmtm5.jpg",
  },
  {
    name: "Corn Chicken Soup",
    price: 10.95,
    description: "chicken, corn, creamy egg mixture",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139840/China%20Center%20Food%20Items/corn_ch_sp_za8o1c.jpg",
  },
  {
    name: "Plain Wonton Soup (L)",
    price: 10.95,
    description: "12 pork filled wontons",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139228/China%20Center%20Food%20Items/plain_wtn_vozv36.jpg",
  },
  {
    name: "Plain Wonton Soup (S)",
    price: 3.0,
    description: "2 pork filled wontons",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139230/China%20Center%20Food%20Items/sm_plain_wtn_zytbuu.jpg",
  },
  {
    name: "Shrimp Sizzling Rice Soup",
    price: 12.95,
    description:
      "crispy sizzling rice, shrimp, mushroom, bamboo shoot, water chestnut, snap peas",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139230/China%20Center%20Food%20Items/siz_sp_laxbpt.jpg",
  },
  {
    name: "Pork Wonton and/or Noodle Soup",
    price: 12.95,
    description:
      "pork filled wontons, pork, bok choy, shitake mushrooms, bamboo shoot, water chestnut. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl: "",
  },
  {
    name: "Chicken Wonton and/or Noodle Soup",
    price: 12.95,
    description:
      "pork filled wontons, chicken, bok choy, shitake mushrooms, bamboo shoot, water chestnut. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139225/China%20Center%20Food%20Items/ch_noodle_cdvhlw.jpg",
  },
  {
    name: "Beef Wonton and/or Noodle Soup",
    price: 12.95,
    description:
      "pork filled wontons, beef, bok choy, shitake mushrooms, bamboo shoot, water chestnut. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139224/China%20Center%20Food%20Items/bf_wtn_gzrs0i.jpg",
  },
  {
    name: "Combo Sizzling Rice Soup",
    price: 13.95,
    description:
      "crispy sizzling rice, chicken, pork, shrimp, mushroom, bamboo shoot, water chestnut",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139230/China%20Center%20Food%20Items/siz_sp_laxbpt.jpg",
  },
  {
    name: "Wor Wonton and/or Noodle Soup",
    price: 13.95,
    description:
      "pork filled wontons, chicken, pork, shrimp, bok choy, shitake mushrooms, bamboo shoot, water chestnut. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366042/China%20Center/Food%20Items/Soup/WWT_lqolqa.jpg",
  },
  {
    name: "Shrimp Wonton and/or Noodle Soup",
    price: 13.95,
    description:
      "pork filled wontons, shrimp, bok choy, shitake mushrooms, bamboo shoot, water chestnut. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139229/China%20Center%20Food%20Items/shr_wtn_lllkrf.jpg",
  },
  {
    name: "Seafood Wonton and/or Noodle Soup",
    price: 14.95,
    description:
      "pork filled wontons, shrimp, fish fillet, squid, bok choy, shitake mushrooms, bamboo shoot, water chestnut. Thick or thin egg noodles optional",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139229/China%20Center%20Food%20Items/sf_wtn_cgeppe.jpg",
  },
  {
    name: "Seafood Sizzling Rice Soup",
    price: 14.95,
    description:
      "crispy sizzling rice, imitation crab meat, fish, shrimp, mushroom, bamboo shoot, water chestnut",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 2,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139230/China%20Center%20Food%20Items/siz_sp_laxbpt.jpg",
  },
  // Fried Rice
  {
    name: "Steamed Rice (S)",
    price: 2.0,
    description: "small steamed rice",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139231/China%20Center%20Food%20Items/st_rice_upqdgb.jpg",
  },
  {
    name: "Steamed Rice (L)",
    price: 3.0,
    description: "large steamed rice",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: true,
    isNut: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677460030/China%20Center/Food%20Items/Fried%20Rice/large_rice_gkqbqy.jpg",
  },
  {
    name: "Chicken Fried Rice",
    price: 9.5,
    description: "fried rice, egg, chicken, green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139225/China%20Center%20Food%20Items/ch_fr_dereo7.jpg",
  },
  {
    name: "Pork Fried Rice",
    price: 9.5,
    description: "fried rice, egg, pork, peas, carrots",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139228/China%20Center%20Food%20Items/p_fr_jyi8a3.jpg",
  },
  {
    name: "Beef Fried Rice",
    price: 9.5,
    description: "fried rice, egg, beef, & green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139223/China%20Center%20Food%20Items/bf_fr_sxxwk1.jpg",
  },
  {
    name: "Vegetable Fried Rice",
    price: 9.5,
    description: "fried rice, egg, beansprouts, peas, carrots, green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152341/veg_fr_gunc1m.jpg",
  },
  {
    name: "Special Fried Rice",
    price: 10.5,
    description: "fried rice, egg, pork, chicken, shrimp, peas, carrots",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152340/sp_fr_ndtnlh.jpg",
  },
  {
    name: "Shrimp Fried Rice",
    price: 10.5,
    description: "fried rice, egg, shrimp, green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 3,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139229/China%20Center%20Food%20Items/shr_fr_fldhxp.jpg",
  },

  //Chow Mein
  {
    name: "Plain Chow Mein",
    price: 9.95,
    description: "stir fried noodles, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139228/China%20Center%20Food%20Items/plain_cm_e2kzgc.jpg",
  },
  {
    name: "Chicken Chow Mein",
    price: 10.95,
    description: "stir fried noodles, chicken, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139224/China%20Center%20Food%20Items/ch_cm_t6e7vu.jpg",
  },
  {
    name: "Chicken Almond Chow Mein",
    price: 10.95,
    description: "stir fried noodles,chicken, almonds, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152341/ch_alm_cm_mgdyfz.jpg",
  },
  {
    name: "Pork Chow Mein",
    price: 10.95,
    description: "stir fried noodles with pork, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139228/China%20Center%20Food%20Items/pork_cm_v55o3p.jpg",
  },
  {
    name: "Vegetable Chow Mein",
    price: 10.95,
    description:
      "stir fried noodles, broccoli, carrots, bokchoy, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139231/China%20Center%20Food%20Items/veg_cm_fstkpj.jpg",
  },
  {
    name: "Special Chow Mein",
    price: 11.5,
    description:
      "stir fried noodles, pork, chicken, shrimp, beansprouts, cabbage, snow peas",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152343/sp_cm_duohsg.jpg",
  },
  {
    name: "Shrimp Chow Mein",
    price: 11.5,
    description: "stir fried noodles, shrimp, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139229/China%20Center%20Food%20Items/shr_cm_g649si.jpg",
  },
  {
    name: "Beef Chow Mein",
    price: 11.5,
    description: "stir fried noodles, beef, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139223/China%20Center%20Food%20Items/bf_cm_fryy1p.jpg",
  },
  {
    name: "Beef Tomato Chow Mein",
    price: 11.5,
    description:
      "stir fried noodles, beef, tomato, green bell pepper, onion, beansprouts, cabbage, tomato sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139231/China%20Center%20Food%20Items/tomato_bf_cm_ig4iub.jpg",
  },
  {
    name: "B.B.Q. Pork Chow Mein",
    price: 10.95,
    description: "stir fried noodles, barbeque pork, beansprouts, cabbage",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139231/China%20Center%20Food%20Items/bbq_p_cm_tmxf6c.jpg",
  },
  {
    name: "Pansit",
    price: 11.5,
    description: "rice stick noodles, egg, beansprouts, choice of protein",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152326/pancit_tebccw.jpg",
  },
  {
    name: "Chow Fun",
    price: 12.95,
    description:
      "thick rice stick noodle, choice of protein, beansprouts, green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152341/bf_chowfun_tgqhia.jpg",
  },
  {
    name: "Seafood Chow Mein",
    price: 12.95,
    description:
      "stir fried noodles, squid, shrimp, beansprouts, cabbage, snow peas",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl: "",
  },

  {
    name: "Singapore Chow Mein",
    price: 13.95,
    description:
      "rice stick noodle stir fried with choice of protein, egg, beansprouts, curry sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139229/China%20Center%20Food%20Items/singapore_cm_s7mrrp.jpg",
  },
  {
    name: "House Pan Fried Noodle Sizzling Plate",
    price: 16.5,
    description:
      "crispy pan fried noodles, special sauce, choice of protein, veggies",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 4,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139227/China%20Center%20Food%20Items/hot_plate_rwrpzz.jpg",
  },
  //Beef
  {
    name: "Beef Broccoli",
    price: 13.95,
    description: "stir fried beef, broccoli",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677366827/China%20Center/Food%20Items/Beef/Brocc_BF_g7kzda.jpg",
  },
  {
    name: "Ginger Beef",
    price: 14.95,
    description: "stir fried beef, ginger, green onion",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152342/ginger_bf_tg9tcf.jpg",
  },
  {
    name: "Beef with Oyster Sauce",
    price: 14.95,
    description: " stir fried beef, oyster sauce, veggies",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef with Tomato",
    price: 14.95,
    description: "stir fried beef, tomatoes, tomato sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139224/China%20Center%20Food%20Items/bf_tomato_fkmsgk.jpg",
  },
  {
    name: "Beef with Beansprouts",
    price: 14.95,
    description: "stir fried beef, beansprouts",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },

  {
    name: "Beef with Chinese Greens",
    price: 14.95,
    description: "stir fried beef, baby bok choy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139223/China%20Center%20Food%20Items/bf_bokchoy_zgiafj.jpg",
  },
  {
    name: "Beef with Tofu",
    price: 14.95,
    description: "stir fried beef, tofu",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139224/China%20Center%20Food%20Items/bf_tofu_veg_r15sk2.jpg",
  },
  {
    name: "Beef with Cashew Nut",
    price: 14.95,
    description: "stir fried beef, cashews, veggies",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Green Pepper Beef",
    price: 14.95,
    description: "stir fried beef, green bell peppers",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef with Assorted Vegetables",
    price: 14.95,
    description: "stir fried beef, assorted vegetables",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Beef Bittermelon",
    price: 14.95,
    description: "stir fried beef, bittermelon",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },
  {
    name: "Curry Beef",
    price: 14.95,
    description: "stir fried beef, veggies, curry sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139225/China%20Center%20Food%20Items/curry_bf_tzwgs5.jpg",
  },
  {
    name: "Kung Pao Beef",
    price: 14.95,
    description: "stir fried beef, hot chilis, veggies, peanuts",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139228/China%20Center%20Food%20Items/kp_bf_hy38rn.jpg",
  },
  {
    name: "Szechuan Beef",
    price: 14.95,
    description: "stir fried beef, hot chilis, cabbage, wood ear mushroom",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139230/China%20Center%20Food%20Items/sze_bf_yqfvar.jpg",
  },
  {
    name: "Mongolian Beef",
    price: 16.95,
    description:
      "stir fried beef, hot chilis, mushrooms, bamboo shoots, green onions",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139228/China%20Center%20Food%20Items/mong_bf_upcvta.jpg",
  },
  {
    name: "Beef Asparagus (Seasonal)",
    price: 16.95,
    description: "stir fried beef, asparagus",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1680498386/China%20Center/Food%20Items/Beef/bf_veg_lqjgfr.jpg",
  },
  {
    name: "Hunan Beef",
    price: 16.95,
    description: "fried beef, hot chilis, bell peppers, onions, carrots",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139227/China%20Center%20Food%20Items/hunan_bf_ewfkgv.jpg",
  },
  {
    name: "Green Bean Beef",
    price: 16.95,
    description: "stir fried beef, green beans",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 5,
    imageUrl: "",
  },
  // Chicken
  {
    name: "Garlic Chicken",
    price: 12.95,
    description:
      "stir fried chicken, hot chilis, garlic, zucchini strips, broccoli, carrots",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152341/gar_ch_eggiku.jpg",
  },
  {
    name: "Kung Pao Chicken",
    price: 12.95,
    description:
      "stir fried chicken, hot chilis, celery, onion, green bell peppers, carrots, peanuts",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139227/China%20Center%20Food%20Items/kp_ch_lizg3i.jpg",
  },
  {
    name: "Chicken with Broccoli",
    price: 12.95,
    description: "stir fried chicken, broccoli",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139224/China%20Center%20Food%20Items/ch_broc_rni9fg.jpg",
  },
  {
    name: "Sweet & Sour Chicken",
    price: 12.95,
    description: "crispy fried chicken, sweet & sour sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139230/China%20Center%20Food%20Items/ss_ch_u2imqu.jpg",
  },
  {
    name: "Cashew Chicken",
    price: 12.95,
    description: "stir fried chicken, veggies, cashews",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139224/China%20Center%20Food%20Items/cashew_ch_ppqscc.jpg",
  },
  {
    name: "Almond Chicken",
    price: 12.95,
    description: "stir fried chicken, veggies, almonds",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Chicken with Assorted Vegetables",
    price: 12.95,
    description: "stir fried chicken, assorted vegetables",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139225/China%20Center%20Food%20Items/ch_veg_nz2qw6.jpg",
  },
  {
    name: "Chicken with Chinese Green",
    price: 12.95,
    description: "stir fried chicken, baby bok choy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Curry Chicken",
    price: 12.95,
    description: "stir fried chicken, veggies, curry sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139225/China%20Center%20Food%20Items/curry_ch_n911m0.jpg",
  },
  {
    name: "Lemon Chicken",
    price: 12.95,
    description: "crispy fried chicken, lemon orange sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Sesame Chicken",
    price: 12.95,
    description: "crispy fried chicken,orange sauce, sesame seeds",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139228/China%20Center%20Food%20Items/sesame_ch_pzl8sc.jpg",
  },
  {
    name: "Orange Chicken",
    price: 12.95,
    description: "crispy fried chicken, orange sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139228/China%20Center%20Food%20Items/or_ch_venppn.jpg",
  },
  {
    name: "Szechuan Chicken",
    price: 12.95,
    description:
      "stir fried chicken, hot chilis, cabbage, bamboo shoots, cloud ear mushrooms",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Pineapple Chicken",
    price: 12.95,
    description: "crispy fried chicken, pineapple orange sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139228/China%20Center%20Food%20Items/pineapple_ch_wa3jqh.jpg",
  },
  {
    name: "General's Chicken",
    price: 14.95,
    description: "crispy fried chicken, hot chilis, broccoli, general sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152341/general_ch_ilubeo.jpg",
  },
  {
    name: "Chicken with Bittermelon",
    price: 14.95,
    description: "stir fried chicken, bittermelon",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139224/China%20Center%20Food%20Items/ch_bittermelon_bzpib6.jpg",
  },
  {
    name: "Chicken with Fresh Mushroom",
    price: 14.95,
    description: "stir fried chicken, mushroom",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139225/China%20Center%20Food%20Items/ch_mushroom_ov6wxy.jpg",
  },
  {
    name: "Green Bean Chicken",
    price: 14.95,
    description: "stir fried chicken, green beans",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl: "",
  },
  {
    name: "Mandarin House Chicken",
    price: 16.95,
    description: "crispy fried bone-in chicken wings, mandarin house sauce",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152342/mandarin_house_chicken_yapr2n.jpg",
  },
  {
    name: "Black Mushroom Chicken",
    price: 16.95,
    description: "stir fried chicken, shitake mushrooms",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152342/blk_mushroom_ch_ugdege.jpg",
  },
  {
    name: "Chicken with Snow Peas",
    price: 16.95,
    description: "stir fried chicken, snow peas",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 6,
    imageUrl: "",
  },
  // Vegetarian
  {
    name: "Kung Pao Tofu",
    price: 12.95,
    description: "tofu - choice of soft or fried, veggies, peanuts",
    isSpicy: true,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 7,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139227/China%20Center%20Food%20Items/kp_tofu_ijgjgu.jpg",
  },
  {
    name: "Mixed Vegetables",
    price: 12.95,
    description: "stir fried vegetables",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 7,
    imageUrl: "",
  },
  {
    name: "Steamed Broccoli",
    price: 12.95,
    description: "broccoli",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 7,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139230/China%20Center%20Food%20Items/st_broc_sefacc.jpg",
  },
  {
    name: "Fried Tofu",
    price: 12.95,
    description: "fried tofu",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 7,
    imageUrl: "",
  },
  {
    name: "Steamed Vegetables",
    price: 12.95,
    description: "Assortment of vegetables",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 7,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139230/China%20Center%20Food%20Items/st_veg_ydknba.jpg",
  },
  {
    name: "Beansprouts",
    price: 12.95,
    description: "beansprouts",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 7,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139223/China%20Center%20Food%20Items/beansprouts_li8keb.jpg",
  },

  {
    name: "Garlic Eggplant with Tofu",
    price: 12.95,
    description: "fried eggplant, fried tofu",
    isSpicy: false,
    isVegan: true,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 7,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139226/China%20Center%20Food%20Items/eggplant_tofu_p9nvk1.jpg",
  },
  // Chop Suey & Egg Foo Yung

  {
    name: "Egg Foo Yung",
    price: 12.95,
    description:
      "egg patties, cabbage, beansprouts, choice of protein, asian gravy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: true,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 8,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139226/China%20Center%20Food%20Items/egg_fu_yung_foih5s.jpg",
  },

  {
    name: "Ho Su Tofu",
    price: 15.95,
    description:
      "tofu - choice of soft or fried, shitake mushrooms, barbecue pork, shrimp, bok choy, beansprouts",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 8,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139227/China%20Center%20Food%20Items/ho_su_tofu_at0i84.jpg",
  },
  {
    name: "Chop Suey",
    price: 15.95,
    description:
      "stir fried beansprouts, assorted vegetables, choice of protein",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 8,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139230/China%20Center%20Food%20Items/sp_cs_khrzyu.jpg",
  },

  // Pork
  {
    name: "Sweet & Sour Pork",
    price: 12.95,
    description: "crispy fried pork, sweet & sour sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139230/China%20Center%20Food%20Items/ss_pork_p4b0ua.jpg",
  },
  {
    name: "Pork with Beansprouts",
    price: 12.95,
    description: "stir fried pork, beansprouts",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Pork with Tofu",
    price: 12.95,
    description: "stir fried pork, tofu - choice of soft or fried",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152341/pork_tofu_ea0spy.jpg",
  },
  {
    name: "Spareribs with Black Bean Sauce",
    price: 14.95,
    description:
      "stir fried spareribs, onions, green bell peppers, black bean sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152341/blk_bn_sparerib_km2ps2.jpg",
  },
  {
    name: "Pork with Chinese Green",
    price: 12.95,
    description: "stir fried pork, baby bok choy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139228/China%20Center%20Food%20Items/pork_bokchoy_ud0ktr.jpg",
  },
  {
    name: "Mapo Tofu",
    price: 12.95,
    description: "steamed tofu, pork, green onions",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139228/China%20Center%20Food%20Items/mapo_tofu_whu9tz.jpg",
  },
  {
    name: "Garlic Eggplant with Pork",
    price: 12.95,
    description: "fried eggplant, pork, garlic",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139226/China%20Center%20Food%20Items/eggplant_tofu_p9nvk1.jpg",
  },
  {
    name: "Pork Bittermelon",
    price: 14.95,
    description: "stir fried pork, bittermelon",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl: "",
  },
  {
    name: "Garlic Pork",
    price: 12.95,
    description: "stir fried pork, hot chilis, veggies, garlic",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139226/China%20Center%20Food%20Items/gar_pork_tcb4ur.jpg",
  },
  {
    name: "Chun King Pork",
    price: 12.95,
    description: "stir fried pork, hot chilis, cabbage, bamboo shoots",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1678220841/China%20Center/Food%20Items/Pork/chun_king_pork_zmkczv.jpg",
  },
  {
    name: "Szechuan Pork",
    price: 12.95,
    description: "stir fried pork, cabbage, bamboo shoots, wood ear mushrooms",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152340/sze_pork_xkzpgw.jpg",
  },
  {
    name: "Barbeque Pork with Broccoli",
    price: 12.95,
    description: "stir fried barbeque pork, broccoli",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 9,
    imageUrl: "",
  },
  // From The Sea

  {
    name: "Shrimp Vegetable",
    price: 15.95,
    description: "stir fried shrimp, veggies",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139229/China%20Center%20Food%20Items/shr_veg_ol3eou.jpg",
  },
  {
    name: "Kung Pao Seafood",
    price: 16.95,
    description:
      "stir fried squid, shrimp, fish fillet, hot chilis, veggies, peanuts",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139227/China%20Center%20Food%20Items/kp_sf_dqd5fq.jpg",
  },
  {
    name: "Shrimp with Chinese Green",
    price: 15.95,
    description: "stir fried shrimp, baby bok choy",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Garlic Shrimp",
    price: 15.95,
    description: "stir fried shrimp, hot chilis, veggies, garlic",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139226/China%20Center%20Food%20Items/gar_shr_dfbouq.jpg",
  },
  {
    name: "Shrimp with Lobster Sauce",
    price: 15.95,
    description: "stir fried shrimp, veggies, lobster sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139229/China%20Center%20Food%20Items/shr_lobster_sauce_ibx3pi.jpg",
  },
  {
    name: "Szechuan Shrimp",
    price: 15.95,
    description: "stir fried shrimp, hot chilis, cabbage, wood ear mushroom",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139231/China%20Center%20Food%20Items/sze_shr_xegmh6.jpg",
  },
  {
    name: "Sweet & Sour Shrimp",
    price: 15.95,
    description: "crispy fried shrimp, sweet & sour sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139230/China%20Center%20Food%20Items/ss_shr_geowwp.jpg",
  },
  {
    name: "Curry Shrimp",
    price: 15.95,
    description: "stir fried shrimp, vegetables, curry sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Shrimp with Black Bean Sauce",
    price: 15.95,
    description: "stir fried shrimp, veggies, black bean sauce",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152341/black_bean_shr_msjr0g.jpg",
  },
  {
    name: "Kung Pao Fish Fillet",
    price: 15.95,
    description: "stir fried fish fillet, hot chilis, veggies, peanuts",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139227/China%20Center%20Food%20Items/kp_fish_a4wnni.jpg",
  },
  {
    name: "Kung Pao Squid",
    price: 15.95,
    description: "stir fried squid, hot chilis, veggies, peanuts",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139227/China%20Center%20Food%20Items/kp_squid_sxmpgl.jpg",
  },
  {
    name: "Fish Fillet with Vegetables",
    price: 15.95,
    description: "stir fried fish fillet, veggies",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1680498418/China%20Center/Food%20Items/From%20The%20Sea/fish_veg_jvbpev.jpg",
  },
  {
    name: "Cashew Shrimp",
    price: 15.95,
    description: "stir fried shrimp, veggies, cashews",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Pan Fried Shrimp",
    price: 17.95,
    description:
      "crispy fried whole shelled shrimp, hot chilis, serrano peppers, ginger, green onions, garlic",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685152341/pan_fried_shrimp_trinva.jpg",
  },
  {
    name: "Shrimp with Green Bean",
    price: 17.95,
    description: "stir fried shrimp, green beans",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Shrimp with Snow Peas",
    price: 17.95,
    description: "stir fried shrimp, snow peas",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139229/China%20Center%20Food%20Items/shr_snowpea_wg3kwu.jpg",
  },
  {
    name: "Shrimp Asparagus",
    price: 17.95,
    description: "stir fried shrimp, asparagus",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139229/China%20Center%20Food%20Items/shr_asp_oxuooh.jpg",
  },
  {
    name: "Seafood Vegetable",
    price: 17.95,
    description: "stir fried shrimp, squid, veggies",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 10,
    imageUrl: "",
  },
  {
    name: "Walnut Shrimp",
    price: 17.95,
    description: "crispy fried shrimp, broccoli, honey, walnuts",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 10,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139227/China%20Center%20Food%20Items/honey_walnut_shr_mexyh0.jpg",
  },
  // Combination Plates
  {
    name: "Combo Plate A",
    price: 13.95,
    description:
      "chicken chow mein, pork fried rice, sweet & sour pork, fried prawns",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 11,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677990415/China%20Center/Food%20Items/Combo%20Plates/A_Edited_md7or1.png",
  },
  {
    name: "Combo Plate B",
    price: 14.95,
    description: "vegetable beef, pork fried rice, egg roll, fried prawns",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 11,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677990784/China%20Center/Food%20Items/Combo%20Plates/b_edited_ja5mzg.png",
  },
  {
    name: "Combo Plate C",
    price: 14.95,
    description:
      "beef broccoli, pork fried rice, sweet & sour pork, fried prawns",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 11,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677990429/China%20Center/Food%20Items/Combo%20Plates/C_Edited_cmlmbo.jpg",
  },
  {
    name: "Combo Plate D",
    price: 14.95,
    description:
      "almond chicken, pork fried rice, sweet & sour pork, fried prawns",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 11,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1677990434/China%20Center/Food%20Items/Combo%20Plates/D_Edited_mfjkbd.jpg",
  },
  // Chinese Family Dinner for 2 or more
  {
    name: "No.1 Family Dinner",
    price: 15.95,
    description: "portion size increases with each additional persons",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 12,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679108559/China%20Center/Food%20Items/Family%20Dinner/family_dinner_1_eyvaqv.png",
  },
  {
    name: "No.2 Family Dinner",
    price: 15.95,
    description: "portion size increases with each additional persons",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 12,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679108559/China%20Center/Food%20Items/Family%20Dinner/family_dinner_2_qjills.png",
  },
  {
    name: "No.3 Family Dinner",
    price: 16.95,
    description: "portion size increases with each additional persons",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 12,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679108559/China%20Center/Food%20Items/Family%20Dinner/family_dinner_3_rpfqzm.png",
  },
  // Lunch Special
  {
    name: "Beef Oyster Sauce (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Sweet & Sour Pork (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Almond Chicken (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Beef Broccoli (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139224/China%20Center%20Food%20Items/broc_bf_lunch_p3kzjs.jpg",
  },
  {
    name: "Beef Green Pepper (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Curry Chicken (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Chicken or Pork Chow Mein (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139225/China%20Center%20Food%20Items/ch_cm_lunch_vdwukq.jpg",
  },
  {
    name: "Chicken Broccoli (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Kung Pao Chicken or Beef (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Garlic Chicken (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Sweet & Sour Chicken (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Chop Suey (Lunch)",
    price: 11.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139229/China%20Center%20Food%20Items/shr_cs_lunch_sarivg.jpg",
  },
  {
    name: "Shrimp Vegetable (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Garlic Shrimp (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139226/China%20Center%20Food%20Items/gar_shr_lunch_isrzkw.jpg",
  },
  {
    name: "Mongolian Beef (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Seafood Vegetable (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Fish Fillet Vegetable (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139226/China%20Center%20Food%20Items/fiosh_veg_lunch_hd7cwp.jpg",
  },
  {
    name: "General Chicken (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl:
      "https://res.cloudinary.com/dsstyuakf/image/upload/v1685139227/China%20Center%20Food%20Items/gen_ch_lunch_evx31b.jpg",
  },
  {
    name: "Kung Pao Fish Fillet (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: true,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: true,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Orange Chicken (Lunch)",
    price: 12.95,
    description: "choice of white rice or fried rice, egg roll",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 13,
    imageUrl: "",
  },
  {
    name: "Glass Wine",
    price: 8,
    description: "chardonnay",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Domestic Beer",
    price: 5,
    description: "Budlight, Coors",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 14,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679108733/China%20Center/Food%20Items/Drinks/coors_and_budlight_dabtpb.jpg",
  },
  {
    name: "Imported Beer",
    price: 6,
    description: "Modelo, Corona, Tsingtao",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 14,
    imageUrl:
      "https://res.cloudinary.com/dsvltch46/image/upload/v1679108848/China%20Center/Food%20Items/Drinks/imported_beer_hpadm1.png",
  },
  {
    name: "Hot Tea",
    price: 2.5,
    description: "oolong",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Ice Tea",
    price: 2.5,
    description: "cold oolong tea",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Soft Drink",
    price: 2.5,
    description:
      "Coke, Sprite, Sunkist, Dr.Pepper, Pepsi, Diet Coke, Diet Dr.Pepper, Pink Lemonade, Yellow Lemonade, Root Beer",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 14,
    imageUrl: "",
  },
  {
    name: "Orange or Apple Juice",
    price: 3.95,
    description: "individually bottled",
    isSpicy: false,
    isVegan: false,
    isVegetarian: false,
    isDairyFree: true,
    isGlutenFree: false,
    isNut: false,
    category_id: 14,
    imageUrl: "",
  },
];

const Categories = [
  {
    id: 1,
    name: "Appetizers",
  },
  {
    id: 2,
    name: "Soups",
  },
  {
    id: 3,
    name: "Fried Rice",
  },
  {
    id: 4,
    name: "Chow Mein",
  },
  {
    id: 5,
    name: "Beef",
  },
  {
    id: 6,
    name: "Chicken",
  },
  {
    id: 7,
    name: "Vegetarian",
  },
  {
    id: 8,
    name: "Chop Suey & Egg Foo Yung",
  },
  {
    id: 9,
    name: "Pork",
  },
  {
    id: 10,
    name: "From The Sea",
  },
  {
    id: 11,
    name: "Combo Plate",
  },
  {
    id: 12,
    name: "Family Dinner",
  },
  {
    id: 13,
    name: "Lunch Special",
  },
  {
    id: 14,
    name: "Drinks",
  },
];

module.exports = {
  Items,
  Categories,
};
